[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_marketplace = "8dsRGc9QXnsvqa5aCm21wS2M9xCPoVqxPpD3j6bysfyt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/nft-marketplace.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  
program = "tests/programs/metaplex_token_metadata_program.so"
[[test.genesis]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"  
program = "tests/programs/mpl_token_auth_rules.so"
